#!/usr/bin/env bash
#displays numbers from 1 to 100. Displays FizzBuzz when the number is a multiple of 3 and 5. Displays Fizz when the number is multiple of 3. Displays Buzz when the number is a multiple of 5. Otherwise, displays the number

n=1

while [ $n -le 100 ]
do
    
f=$(( n % 3 )) 
b=$(( n % 5 ))

#if [ $f = $b ]
if [ $f = 0 ] && [ $b = 0 ]
then
    echo "FizzBuzz"
     
 elif [ $f = 0 ] 
 then
     echo "Fizz"
 elif [ $b = 0 ]
 then
     echo "Buzz"

			   
 else
     echo $n
 fi


 (( n++ ))
done
