#!/usr/bin/env bash
#Displays the time for 12 hours and 59 minutes. Displays hours from 0 to 12. Displays minutes from 1 to 59. Must use while loop.
hour=0
minute=1
while [ $hour -lt 13 ]
do
    echo "Hour: $hour"
    (( hour++ ))

if [ $minute -eq 60 ]
then
    minute=1
fi

    
while [ $minute -lt 60 ]
do
    echo "$minute"                                                                          
 (( minute++ ))
    

  
 #minute=$(( minute + 1 ))  

done
done


