#!/usr/bin/env bash
#Displays the content of the current directory in a list format where only the part of the name after the first dash is displayed. Must use for loop. Must not display hidden files

for ls in *
do
    echo "$ls" | cut -d- -f2



	#tr -d "[:digit:]-"
    

done





