#!/usr/bin/env bash
# Installs HAproxy on my server and configures it
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.5
sudo apt-get -y install haproxy=2.5.\*
sudo echo -e "\nfrontend myfrontend\n
\tbind 0.0.0.0:80\n
\tdefault_backend myservers\n
\nbackend myservers\n
\tserver 3613-web-01 100.26.28.112:80 check\n
\tserver 3613-web-02 54.197.30.253:80 check\n
\tbalance roundrobin" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
